# Paso 1

In [20]:
import json
import re
import pandas as pd

In [23]:
df = pd.read_json('catalogo_tp3.jsonl', lines=True)

In [24]:
total_inicial = len(df)
print(f"Total de registros iniciales: {total_inicial}")

Total de registros iniciales: 8747

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8747 entries, 0 to 8746
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   source_url      8747 non-null   str
 1   slug            8747 non-null   str
 2   title           8747 non-null   str
 3   authors         8747 non-null   object
 4   genres          8747 non-null   object
 5   seed_genre      8747 non-null   str
 6   series          2316 non-null   str
 7   series_number   2298 non-null   float64
 8   cover_url       8747 non-null   str
 9   synopsis        8746 non-null   str
 10  synopsis_chars  8747 non-null   int64
 11  scraped_at      8747 non-null   datetime64[us, UTC]
dtypes: datetime64[us, UTC](1), float64(1), int64(1), object(2), str(7)
memory usage: 820.2+ KB

In [26]:
df.head()

,source_url,slug,title,authors,genres,seed_genre,series,series_number,cover_url,synopsis,synopsis_chars,scraped_at
0,https://ww3.lectulandia.com/book/de-la-caverna...,de-la-caverna-al-cosmos,De la caverna al cosmos,[Eudald Carbonell],"[Arqueología, Divulgación, Ensayo]",arqueologia,NaN,NaN,https://assets.lectulandia.com/b/ab/Eudald%20C...,La Humanidad ha entrado en una nueva fase evol...,998,2026-10-17 23:11:56+00:00
1,https://ww3.lectulandia.com/book/quienes-somos...,quienes-somos-y-como-hemos-llegado-hasta-aqui,Quiénes somos y cómo hemos llegado hasta aquí,[David Reich],"[Arqueología, Biología, Ciencias naturales, En...",arqueologia,NaN,NaN,https://assets.lectulandia.com/b/ab/David%20Re...,La extracción de ADN de los huesos de nuestros...,1285,2026-10-17 23:11:58+00:00
2,https://ww3.lectulandia.com/book/teotihuacan/,teotihuacan,Teotihuacan,[Eduardo Matos Moctezuma],"[Arqueología, Arte, Ciencias sociales, Ensayo,...",arqueologia,NaN,NaN,https://assets.lectulandia.com/b/ab/Eduardo%20...,Teotihuacan es la primera gran ciudad del cent...,1070,2026-10-17 23:12:01+00:00
3,https://ww3.lectulandia.com/book/tiro-y-las-co...,tiro-y-las-colonias-fenicias-de-occidente,Tiro y las colonias fenicias de Occidente,[M.ª Eugenia Aubet],"[Arqueología, Economía, Ensayo, Historia, Polí...",arqueologia,NaN,NaN,https://assets.lectulandia.com/b/ab/M%20Eugeni...,Entre los siglos VIII y VI a. C. los fenicios ...,1875,2026-10-17 23:12:03+00:00
4,https://ww3.lectulandia.com/book/la-maldicion-...,la-maldicion-del-hombre-mono,La maldición del hombre mono,[Emiliano Bruner],"[Arqueología, Ensayo, Psicología, Sociología]",arqueologia,NaN,NaN,https://assets.lectulandia.com/b/ab/Emiliano%2...,Las raíces evolutivas del sufrimiento humano\n...,1613,2026-10-17 23:12:05+00:00

In [31]:
(df['synopsis'] == "").sum()

np.int64(0)

In [32]:
# detectar filas con sinapsis = a NaN
df[df['synopsis'].isnull()]

,source_url,slug,title,authors,genres,seed_genre,series,series_number,cover_url,synopsis,synopsis_chars,scraped_at
7969,https://ww3.lectulandia.com/book/calvario/,calvario,Calvario,[Alejandro Sawa],"[Drama, Teatro]",teatro,NaN,NaN,https://assets.lectulandia.com/b/ab/Alejandro%...,NaN,0,2026-10-18 22:48:58+00:00

Hay una sola fila con sinapsis vacia

In [33]:
df = df.dropna(subset=["synopsis"])
df = df[df["synopsis"].astype(str).str.strip() != ""]

In [34]:
# detectar cuantas y eliminar las filas con slug duplicados
df.duplicated(subset=['slug']).sum()

np.int64(0)

No hay libros duplicados

In [35]:
df = df.drop_duplicates(subset=["slug"], keep="first")

In [36]:
len(df)

8746

In [ ]:
# Normalizar espacios en blanco (reemplazar saltos de línea y tabs por un único espacio)
df["synopsis"] = df["synopsis"].astype(str).apply(lambda x: re.sub(r"\s+", " ", x).strip())
df["title"] = df["title"].astype(str).apply(lambda x: re.sub(r"\s+", " ", x).strip())

In [ ]:
# Contar duplicados exactos de sinopsis
sinopsis_duplicadas = df[df.duplicated(subset=["synopsis"], keep=False)]
print(f"Registros con sinopsis iguales: {len(sinopsis_duplicadas)}")

Registros involucrados en sinopsis idénticas: 131

In [39]:
# Conservar una sola versión por sinopsis
df = df.drop_duplicates(subset=["synopsis"], keep="first")
print(f"Libros eliminados por sinopsis iguales: {len(sinopsis_duplicadas)}")

Libros eliminados por sinopsis iguales: 131